<?php
/**
 * @package    Leytech_EstimatedDeliveryCountdown
 * @author     Chris Nolan (chris@leytech.co.uk)
 * @copyright  Copyright (c) 2018 Chris Nolan
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$helper = $this->helper('leytech_estimated_delivery_countdown');
if(!$helper->canShowCountdown()){
    return;
}
$estimatedDelivery = $helper->getEstimatedDeliveryDate('EEEE, d MMM');
$cutOff = $helper->getNextCutOff();
?>
<div id="delivery-countdown">
    <p><strong>Want it delivered by <?php echo $estimatedDelivery; ?>?</strong> Order within <span id="clock"></span> and choose <strong>Express delivery</strong> at checkout.</p>
    <div id="countdown"></div>
</div>
<script type="text/javascript">
    jQuery(function($){
        $('#countdown').countdown('<?php echo $cutOff; ?>')
        .on('update.countdown', function(event) {
            <?php if ($helper->getShowSeconds()) : ?>
            var format = '%-S secs';
            <?php else : ?>
            var format = '';
            <?php endif; ?>
            if(event.offset.totalMinutes > 0) {
                format = '%-M mins ' + format;
            }
            if(event.offset.totalHours > 0) {
                format = '%-H hours ' + format;
            }
            if(event.offset.totalDays > 0) {
                format = '%-D days ' + format;
            }
            $('#clock').html(event.strftime(format));
        })
        .on('finish.countdown', function(event) {
            $('#delivery-countdown').hide();
        });
    });
</script>